
services:
  fastapi:
    build: .
    container_name: fastapi
    expose:
      - "80"  # Expose FastAPI app on port 80 inside the container

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Expose Nginx on port 80 of the host machine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount the Nginx config file
    depends_on:
      - fastapi  # Ensure Nginx starts after FastAPI container
