name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up DigitalOcean CLI (doctl)
        run: |
          curl -sSL https://github.com/digitalocean/doctl/releases/download/v1.86.0/doctl-1.86.0-linux-amd64.tar.gz | tar xz
          sudo mv doctl /usr/local/bin
          doctl version

      - name: Authenticate to DigitalOcean API
        run: |
          echo "${{ secrets.DO_API_TOKEN }}" | doctl auth init -t

      - name: Deploy Application to DigitalOcean
        run: |
          doctl apps create --spec .do/app.yaml  # Modify with your app's spec or deploy command
