name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up DigitalOcean API token
        run: |
          echo "${{ secrets.DO_API_TOKEN }}" > ~/.do_token
          chmod 600 ~/.do_token
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}

      - name: Deploy Application to DigitalOcean App Platform
        run: |
          doctl auth init --access-token $DO_API_TOKEN
          # Assuming you have your app.yaml or deployment specs
          doctl apps create --spec .do/app.yaml
